"""Load pipeline configuration from YAML."""

import contextlib
import importlib
import inspect
import logging
from typing import Any, Dict

from autopipe.schemas.models import PipelineConfig

from .pipeline import Pipeline
from .step import Step

logger = logging.getLogger(__name__)

# Single source of truth for builtin step aliases. Both the loader and
# `autopipe validate` must resolve step types through this map so that a
# config generated by `autopipe create` always validates.
#
# COVERAGE RULE (enforced by tests/unit/test_step_alias_coverage.py):
# every public Step subclass shipped in the library must be addressable
# here, so YAML pipelines can use the whole step library — not just a
# privileged few. Quarantine exception: PiCodingStep stays explicit-import
# only.
BUILTIN_ALIASES: Dict[str, str] = {
    # Core builtins
    "print": "autopipe.core.steps.PrintStep",
    "llm": "autopipe.core.steps.LLMStep",
    "visualization": "autopipe.core.steps.VisualizationStep",
    "feature_engineering": "autopipe.core.steps.FeatureEngineeringStep",
    "fe": "autopipe.core.steps.FeatureEngineeringStep",
    # Bundled scikit-learn sample datasets (iris, diabetes). For a real
    # CSV/parquet/SQL source use `data_loader`, which reads via `source:`.
    "sample_data_loader": "autopipe.core.steps.DataLoaderStep",
    # Data handling (steps.data)
    "data_loader": "autopipe.steps.data.DataLoaderStep",
    "data_validator": "autopipe.steps.data.DataValidatorStep",
    "preprocessing": "autopipe.steps.data.DataPreprocessorStep",
    "feature_selection": "autopipe.steps.data.FeatureSelectionStep",
    # Training (steps.training)
    "sklearn_training": "autopipe.steps.training.SklearnTrainerStep",
    "hyperparameter_tuning": "autopipe.steps.training.HyperparameterTunerStep",
    # Deep learning (steps.deep_learning) — canonical trainers
    "pytorch_training": "autopipe.steps.deep_learning.PyTorchTrainerStep",
    "tensorflow_training": "autopipe.steps.deep_learning.TensorFlowTrainerStep",
    "transfer_learning": "autopipe.steps.deep_learning.TransferLearningStep",
    # Resampling / validation (steps.cross_validation)
    "cross_validation": "autopipe.steps.cross_validation.CrossValidationStep",
    "nested_cross_validation": "autopipe.steps.cross_validation.NestedCrossValidationStep",
    "data_splitter": "autopipe.steps.cross_validation.DataSplitterStep",
    "stratified_group_kfold": "autopipe.steps.cross_validation.StratifiedGroupKFoldStep",
    "bootstrap_validation": "autopipe.steps.cross_validation.BootstrapValidatorStep",
    # Evaluation (steps.evaluation)
    "model_evaluation": "autopipe.steps.evaluation.ModelEvaluatorStep",
    "explainability": "autopipe.steps.evaluation.ExplainabilityStep",
    "drift_detection": "autopipe.steps.evaluation.DriftDetectionStep",
    # Model explainability (steps.explainability)
    "shap_explainer": "autopipe.steps.explainability.SHAPExplainerStep",
    "lime_explainer": "autopipe.steps.explainability.LIMEExplainerStep",
    "permutation_importance": "autopipe.steps.explainability.PermutationImportanceStep",
    "partial_dependence": "autopipe.steps.explainability.PartialDependenceStep",
    "feature_importance": "autopipe.steps.explainability.FeatureImportanceStep",
    "attention_visualizer": "autopipe.steps.explainability.AttentionVisualizerStep",
    "explainability_pipeline": "autopipe.steps.explainability.ExplainabilityPipeline",
    # Monitoring (monitoring.drift_detection)
    "statistical_drift_detection": "autopipe.monitoring.drift_detection.StatisticalDriftDetectorStep",
    "target_drift_detection": "autopipe.monitoring.drift_detection.TargetDriftDetectorStep",
    "prediction_drift_monitoring": "autopipe.monitoring.drift_detection.PredictionDriftMonitorStep",
    "drift_dashboard": "autopipe.monitoring.drift_detection.DriftDashboardStep",
}


def resolve_step_type(step_type: str) -> str:
    """Resolve a builtin alias to its full dotted class path."""
    return BUILTIN_ALIASES.get(step_type, step_type)


# Pipeline configs are untrusted input (they arrive from YAML files and the
# dashboard API). Only these package roots may ever be imported as steps —
# otherwise a config line `type: os.system` becomes remote code execution.
TRUSTED_STEP_ROOTS = (
    "autopipe.steps.",
    "autopipe.core.steps.",
    "autopipe.monitoring.",
    "autopipe.evaluation",
)

# Quarantined host-capability steps (I16): documented as explicit-Python-import
# only (CHANGELOG 0.2.0, NORTH_STAR — agents are planners/clients, not hosts).
# The trusted roots above intentionally cover these modules for operator code,
# so config-driven instantiation is denied here — one gate every config path
# (CLI run/validate, YAML load, dashboard admission) passes through.
QUARANTINED_STEP_MODULES = (
    "autopipe.steps.pi_coding",
    "autopipe.steps.pi_coding_models",
)


def import_class(class_path: str) -> type:
    """Import a Step class from a dotted path within trusted package roots."""
    resolved = resolve_step_type(class_path)
    if not resolved.startswith(TRUSTED_STEP_ROOTS):
        raise ValueError(
            f"Step type '{class_path}' is not allowed. Trusted roots: "
            f"{', '.join(TRUSTED_STEP_ROOTS)}. Register custom steps inside "
            "the autopipe.* package namespace."
        )
    module_name, class_name = resolved.rsplit(".", 1)
    if any(module_name == q or module_name.startswith(f"{q}.") for q in QUARANTINED_STEP_MODULES):
        raise ValueError(
            f"Step type '{class_path}' is quarantined: config-driven loading is "
            "forbidden; import it explicitly from Python if you are an operator."
        )
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as e:
        raise ValueError(f"Failed to import module '{module_name}': {e}") from e
    try:
        step_cls: type = getattr(module, class_name)
    except AttributeError as e:
        raise ValueError(f"Class '{class_name}' not found in module '{module_name}'") from e
    return step_cls


def load_step_from_config(step_config: Dict[str, Any]) -> Step:
    """Create a Step instance from a config dictionary.

    Config format:
        name: step_name
        type: dotted.path.to.StepClass  or builtin alias
        params: { ... }  # passed to constructor
        depends_on: [list of step names]
    """
    name = step_config["name"]
    step_type = resolve_step_type(step_config.get("type", BUILTIN_ALIASES["print"]))
    params = step_config.get("params", {})
    depends_on = list(step_config.get("depends_on", []))
    input_bindings = dict(step_config.get("input_bindings", {}) or {})
    # Bound upstream steps are dependencies by definition.
    for upstream in input_bindings.values():
        if upstream not in depends_on:
            depends_on.append(upstream)

    # Import the class
    cls = import_class(step_type)

    # Instantiate with params
    try:
        step: Step = cls(name=name, depends_on=depends_on, **params)
        # Attach bindings for the run loop (named-input resolution).
        with contextlib.suppress(AttributeError):
            step.input_bindings = input_bindings
    except TypeError as e:
        raise ValueError(f"Failed to instantiate {step_type} with params {params}: {e}") from e

    return step


def _validate_input_bindings(pipeline: Pipeline) -> None:
    """Reject bindings whose key is not a run() parameter (load-time, I8).

    A step whose ``run()`` declares ``**kwargs`` accepts any binding key;
    otherwise every key in ``input_bindings`` must match a declared parameter,
    so a typo like ``modle`` fails at load instead of at run time.
    """
    for step in pipeline.steps.values():
        bindings = getattr(step, "input_bindings", None) or {}
        if not bindings:
            continue
        sig = inspect.signature(step.run)
        if any(p.kind is inspect.Parameter.VAR_KEYWORD for p in sig.parameters.values()):
            continue
        for key in bindings:
            if key not in sig.parameters:
                raise ValueError(
                    f"Step '{step.name}' has no run() parameter '{key}'; "
                    f"available: {sorted(sig.parameters)}"
                )


def load_pipeline_from_config(config: Dict[str, Any]) -> Pipeline:
    """Create a Pipeline from a config dictionary.

    The config is validated through ``PipelineConfig`` (unique step names,
    no self-dependencies, dependencies exist, no unknown keys) before any step
    class is imported or instantiated. Binding parameters are checked against
    each step's ``run()`` signature and the execution plan is resolved, so a
    loadable pipeline is an executable one (invariant I8).
    """
    validated = PipelineConfig.model_validate(config)
    pipeline = Pipeline(validated.name)

    for step_model in validated.steps:
        step = load_step_from_config(
            {
                "name": step_model.name,
                "type": step_model.type,
                "params": step_model.params,
                "depends_on": step_model.depends_on,
                "input_bindings": dict(step_model.inputs),
            }
        )
        pipeline.add_step(step)

    _validate_input_bindings(pipeline)
    order = list(pipeline.execution_order)  # raises ValueError on a cycle
    logger.debug("Pipeline %s is executable: %d step(s)", pipeline.name, len(order))
    return pipeline


def load_executable_pipeline(config: Dict[str, Any]) -> Pipeline:
    """Backward-compatible alias for ``load_pipeline_from_config``.

    Plan resolution and binding checks now live in the loader itself, so this
    thin wrapper remains only for existing callers (CLI validate, run
    admission).
    """
    return load_pipeline_from_config(config)
