"""Load pipeline configuration from YAML."""

import contextlib
import importlib
import logging
from typing import Any, Dict

from autopipe.schemas.models import PipelineConfig

from .pipeline import Pipeline
from .step import Step

logger = logging.getLogger(__name__)

# Single source of truth for builtin step aliases. Both the loader and
# `autopipe validate` must resolve step types through this map so that a
# config generated by `autopipe create` always validates.
BUILTIN_ALIASES: Dict[str, str] = {
    "print": "autopipe.core.steps.PrintStep",
    "llm": "autopipe.core.steps.LLMStep",
    "data_loader": "autopipe.steps.data.DataLoaderStep",
    "visualization": "autopipe.core.steps.VisualizationStep",
    "feature_engineering": "autopipe.core.steps.FeatureEngineeringStep",
    "fe": "autopipe.core.steps.FeatureEngineeringStep",
}


def resolve_step_type(step_type: str) -> str:
    """Resolve a builtin alias to its full dotted class path."""
    return BUILTIN_ALIASES.get(step_type, step_type)


# Pipeline configs are untrusted input (they arrive from YAML files and the
# dashboard API). Only these package roots may ever be imported as steps —
# otherwise a config line `type: os.system` becomes remote code execution.
TRUSTED_STEP_ROOTS = (
    "autopipe.steps.",
    "autopipe.core.steps.",
    "autopipe.monitoring.",
    "autopipe.evaluation",
)


def import_class(class_path: str):
    """Import a Step class from a dotted path within trusted package roots."""
    resolved = resolve_step_type(class_path)
    if not resolved.startswith(TRUSTED_STEP_ROOTS):
        raise ValueError(
            f"Step type '{class_path}' is not allowed. Trusted roots: "
            f"{', '.join(TRUSTED_STEP_ROOTS)}. Register custom steps inside "
            "the autopipe.* package namespace."
        )
    module_name, class_name = resolved.rsplit(".", 1)
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as e:
        raise ValueError(f"Failed to import module '{module_name}': {e}") from e
    try:
        return getattr(module, class_name)
    except AttributeError as e:
        raise ValueError(f"Class '{class_name}' not found in module '{module_name}'") from e


def load_step_from_config(step_config: Dict[str, Any]) -> Step:
    """Create a Step instance from a config dictionary.

    Config format:
        name: step_name
        type: dotted.path.to.StepClass  or builtin alias
        params: { ... }  # passed to constructor
        depends_on: [list of step names]
    """
    name = step_config["name"]
    step_type = resolve_step_type(step_config.get("type", BUILTIN_ALIASES["print"]))
    params = step_config.get("params", {})
    depends_on = list(step_config.get("depends_on", []))
    input_bindings = dict(step_config.get("input_bindings", {}) or {})
    # Bound upstream steps are dependencies by definition.
    for upstream in input_bindings.values():
        if upstream not in depends_on:
            depends_on.append(upstream)

    # Import the class
    cls = import_class(step_type)

    # Instantiate with params
    try:
        step = cls(name=name, depends_on=depends_on, **params)
        # Attach bindings for the run loop (named-input resolution).
        with contextlib.suppress(AttributeError):
            step.input_bindings = input_bindings
    except TypeError as e:
        raise ValueError(f"Failed to instantiate {step_type} with params {params}: {e}") from e

    return step


def load_pipeline_from_config(config: Dict[str, Any]) -> Pipeline:
    """Create a Pipeline from a config dictionary.

    The config is validated through ``PipelineConfig`` (unique step names,
    no self-dependencies, dependencies exist) before any step class is
    imported or instantiated.
    """
    validated = PipelineConfig.model_validate(config)
    pipeline = Pipeline(validated.name)

    for step_model in validated.steps:
        step = load_step_from_config(
            {
                "name": step_model.name,
                "type": step_model.type,
                "params": step_model.params,
                "depends_on": step_model.depends_on,
                "input_bindings": dict(step_model.inputs),
            }
        )
        pipeline.add_step(step)

    return pipeline
