// Context compaction hook: suggest which files to drop
module.exports = async function suggestCompactHook(context) {
    const files = context.openFiles || [];
    const suggestions = [];

    // Suggest dropping large autogenerated or design docs
    for (const f of files) {
        if (f.endsWith(".png") || f.endsWith(".jpg")) {
            suggestions.push(f);
        }
        if (f.includes("DASHBOARD_COMPLETE_DESIGN.md") || f.includes("TRANSFORMATION_SUMMARY.md")) {
            suggestions.push(f);
        }
    }

    if (suggestions.length === 0) {
        return {};
    }

    return {
        notifications: [{
            type: "info",
            title: "Context Compaction",
            message: `Consider removing from context:\n${suggestions.join("\n")}`
        }]
    };
};
